### ISSUE TITLE
no ability to set track_and_verify_wals_in_manifest option

### ISSUE THREAD

**Issue by snirs90** [linxGnu/grocksdb#103]
Hi,

first I would like to say thank you for this package bridging rocksdb to Go.

per the recommendation in https://github.com/facebook/rocksdb/wiki/Track-WAL-in-MANIFEST
to set "track_and_verify_wals_in_manifest" to true (default is false),
I saw that there's no ability to set this option, is it possible to add a getter/setter for this option property?

Thanks!

**Comment by linxGnu** [comment]
@snirs90 I could not find the api in C interface. Guess that, it's only available for C++ right now
