### ISSUE TITLE
support a non-hacky way to override link flags

### ISSUE THREAD

**Issue by yihuang** [linxGnu/grocksdb#104]
I have more situations that need to customize the link flags, for example recently I cross compiled the app to mingwW64 with the help of nixpkgs, but there I have to link with `-lrocksdb-shared`.
currently there's a way to suppress the builtin link flags, which is the `testing` build tag, it works perfectly right now, it's just the name feels hacky, shall we support sth like `grocksdb_no_link` build tag, where there's no builtin link flags, user can supply with `CGO_LDFLAGS` env var?

**Comment by linxGnu** [comment]
Sound great to me @yihuang please feel free to make a PR

**Comment by yihuang** [comment]
@linxGnu there's another thing, there are two APIs are not exported on windows(https://github.com/facebook/rocksdb/pull/11217), currently we use a fork to support windows, do you want me to submit to upstream for windows support?

**Comment by linxGnu** [comment]
Yes please (although I need to update CI later)
