### ISSUE TITLE
failed to compile: library not found for -lsnappy

### ISSUE THREAD

**Issue by lichadehehehe** [linxGnu/grocksdb#115]
Hi. Many thanks wholeheartedly for maintaining this repo, as the original Gorocksdb is no longer compatible with the newer version of RocksDB.
I've encountered the following issue during compiling.
 
```
/opt/homebrew/cellar/go/1.20.5/libexec/pkg/tool/darwin_arm64/link: running cc failed: exit status 1
ld: library not found for -lsnappy
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Environment: MacOS Ventura with Apple Silicon
Both RocksDB and its dependencies (including snappy) are installed via Homebrew.

Any assistance is greatly appreciated.

**Comment by linxGnu** [comment]
@lichadehehehe 

Please try to install pkg_config:

```bash
brew install pkg-config
```

(Optionally) Configure pkg-config:
```bash
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/lib/pkgconfig:/opt/homebrew/lib/pkgconfig
```

**Comment by lichadehehehe** [comment]
Thanks for the follow-up.
`pkg-config 0.29.2_3 is already installed and up-to-date.`
I've also configured the pkg-config export command, still can't find Snappy 
My snappy is located in `/opt/homebrew/Cellar/snappy/1.1.10` 
The structure of the directory is as follows:
<img width="292" alt="image" src="https://github.com/linxGnu/grocksdb/assets/83261960/ff7ac886-1861-419a-856b-eae00e8b1524">
There's no pkg-config directory inside the `lib`, which could be the reason why it's acting odd. If you might know how to solve this please assist as I'll also keep digging it.

**Comment by lichadehehehe** [comment]
It seems like homebrew on macOS, while still being a convenient dependency installation tool, would still create some usual kerfuffles when dealing with dependency paths. 

I've decided just manually dictates where the missing packages are using `-L `flags, I think this is way much easier. 

For instance, if `snappy` is missing, don't do `-lsnappy`, find wherever snappy is installed on your machine, copy the absolute path of the` lib` directory, and use it with the `-L` flag while building. 

For example,  instead of doing `CGO_LDFLAGS="-L/path/to/rocksdb -lrocksdb -lstdc++ -lm -lz -lsnappy -llz4 -lzstd"` , I'll do `CGO_LDFLAGS="-L/path/to/rocksdb -lrocksdb -lstdc++ -lm -lz -L/opt/homebrew/Cellar/snappy/1.1.10/lib -llz4 -lzstd"`. By doing this you can dictates where Exactly the dependency is and stop the terminal from yelling `library not found ` to you every again.

In my case, I set the CGO_LDFLAGS by doing `export CGO_LDFLAGS="-L/opt/homebrew/Cellar/rocksdb/8.1.1/lib -L/opt/homebrew/Cellar/zstd/1.5.5/lib -L/opt/homebrew/Cellar/lz4/1.9.4/lib -L/opt/homebrew/Cellar/snappy/1.1.10/lib"
`. Be advised this only works for my local environment and people still need to find out the exact local path of the dependencies and which -L flag they need to include.
