### ISSUE TITLE
ld: library not found for -lrocksdb

### ISSUE THREAD

**Issue by WillJE** [linxGnu/grocksdb#116]
enviroment:
Environment: MacOS Ventura with Apple Silicon
Both RocksDB(7.7.3) and its dependencies (including snappy) are installed via Homebrew.
using grocksdb 1.7.12

compile command:
```
CGO_CFLAGS="-I/opt/homebrew/Cellar/rocksdb/7.7.3/include" \
CGO_LDFLAGS="-L/opt/homebrew/Cellar/rocksdb/7.7.3 -lrocksdb -lstdc++ -lm -lz -lsnappy -llz4 -lzstd" \
  go build
```
got this error 
```
/usr/local/go/pkg/tool/darwin_arm64/link: running clang failed: exit status 1
ld: library not found for -lrocksdb
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

any suggesstions?

**Comment by linxGnu** [comment]
@WillJE have you tried
```
CGO_LDFLAGS="-L/opt/homebrew/Cellar/rocksdb/7.7.3/lib
```

**Comment by linxGnu** [comment]
According to the error. I believe that the problem is the linker dir you specify. It should point to `rocksdb/7.7.3/lib` rather than just `rocksdb/7.7.3`
