### ISSUE TITLE
Include library files in repository 

### ISSUE THREAD

**Issue by saeid-a** [linxGnu/grocksdb#119]
I have a recommendation on how we can improve the build and stability of this library. Our RocksDB library files (`librocksdb.a`) depend on the operating system's RocksDB files, which can cause inconsistencies. For instance, if you have Ubuntu 23.04 on your local machine with version `librocksdb7.8` and GitHub Action's `ubuntu-latest` has version `librocksdb6.11`, they will both be incompatible with specific versions of `grocksdb.` We have two options: we can change the `grocksdb` library to avoid giving errors based on the build and version particularities of the currently installed library, or we can have each version of the library directly usable and have the same library version. This method has been successfully used in other libraries like [confluent-kafka-go](https://github.com/confluentinc/confluent-kafka-go). You can check out the libraries at https://github.com/confluentinc/confluent-kafka-go/tree/master/kafka/librdkafka_vendor.

**Comment by linxGnu** [comment]
@saeid-a Thank you for the recommendation.

Unfortunately, it's not suitable for grocksdb for several reasons:

1. Confluent maintains librdkafka. They have right and trust from the community to embed static librdkafka. I don't own rocksdb, embedding it will raise security concern around users
2. Static lib size is not trivial. It will burden existing CI/CD pipeline.

In this way, I would like to close this ticket. Please feel free to recommend and contribute to grocksdb in any way. Thank you
