### ISSUE TITLE
Documentation improvments: When should Destroy be called for db option types ? 

### ISSUE THREAD

**Issue by aureliar8** [linxGnu/grocksdb#123]
HI,

First thank you for maintaining this binding. 

I have a small question regarding where one should call `Destroy()` on option objects. 

I have the following code 
```go
opts := grocksdb.NewDefaultOptions()
tableOpts := grocksdb.NewDefaultBlockBasedTableOptions()
cache := grocksdb.NewLRUCache(8 * 1024 * 1024)
tableOpts.SetBlockCache(cache)
opts.SetBlockBasedTableFactory(tableOpts)

db := grocksdb.OpenDb(opts ,"foo.rocksdb")
// ...
db.Close()
```

At which point in this code can I safely call `Destroy()` on `opts`, `tableOpts` and `cache` ? 
Should I wait after the db is closed or can I destroy them after the db is opened ?

**Comment by linxGnu** [comment]
@aureliar8 due to the complexity of object lifetime and no official document about it, I highly recommend you keep opts, tableOpts, cache until db is closed. Especially cache.
