### ISSUE TITLE
Is it possible to implement CompactFiles ?

### ISSUE THREAD

**Issue by snirs90** [linxGnu/grocksdb#128]
I've saw that there's an option to manual compact specific files with the API of CompactFiles
https://github.com/facebook/rocksdb/wiki/Manual-Compaction#compactfiles

is it possible to implement it in this library?

Thanks!

**Comment by linxGnu** [comment]
Hi @snirs90 

RocksDB did not expose CompactFiles API yet: https://github.com/facebook/rocksdb/blob/main/include/rocksdb/c.h
