### ISSUE TITLE
Help for dummies? ./cache.go:25:12: could not determine kind of name for C.rocksdb_cache_create_hyper_clock

### ISSUE THREAD

**Issue by CRossel87a** [linxGnu/grocksdb#139]
Hi. I have gorocksdb as a dependency for other project and experiencing compiling issues that are difficult to pinpoint.

System: Ubuntu 20

This folder has all the includes
 echo $CGO_CFLAGS
-I/include/rocksdb/

This is the rocksdb repository with compiled lib
echo $CGO_LDFLAGS
-L/root/dev/rocksdb -lrocksdb -lstdc++ -lm -lz -lbz2 -lsnappy -llz4 -lzstd

Getting:
# go build
# github.com/linxGnu/grocksdb
./cache.go:25:12: could not determine kind of name for C.rocksdb_cache_create_hyper_clock
./cache.go:31:12: could not determine kind of name for C.rocksdb_cache_create_hyper_clock_opts
./cache.go:148:6: could not determine kind of name for C.rocksdb_hyper_clock_cache_options_create
./cache.go:204:2: could not determine kind of name for C.rocksdb_hyper_clock_cache_options_destroy
./cache.go:154:2: could not determine kind of name for C.rocksdb_hyper_clock_cache_options_set_capacity
./cache.go:189:2: could not determine kind of name for C.rocksdb_hyper_clock_cache_options_set_estimated_entry_charge
./cache.go:199:2: could not determine kind of name for C.rocksdb_hyper_clock_cache_options_set_memory_allocator
./cache.go:194:2: could not determine kind of name for C.rocksdb_hyper_clock_cache_options_set_num_shard_bits
./cache.go:142:5: could not determine kind of name for C.rocksdb_hyper_clock_cache_options_t

**Comment by nddeluca** [comment]
@CRossel87a likely an incompatible version.   The release notes at https://github.com/linxGnu/grocksdb/releases should help you determine what grocksdb version and/or what rocksdb version to use
