### ISSUE TITLE
Is it safe enough to use refGoBytes()

### ISSUE THREAD

**Issue by aaronyuan** [linxGnu/grocksdb#140]
Hi, in the Get() function, it uses refGoBytes() to convert []bytes to C.char, involving the use of unsafe.Pointer. Is it possible that a key has been garbage collected, posing a risk of cKey pointing to null?

**Comment by aaronyuan** [comment]
Hi @linxGnu
`C.rocksdb_get(db.c, opts.c, cKey, C.size_t(len(key)), &cValLen, &cErr)`
Does calling into C go beyond the scope of Go?

**Comment by linxGnu** [comment]
@aaronyuan 

Here is the signature of rocksdb_get:

```C
extern ROCKSDB_LIBRARY_API char* rocksdb_get(
    rocksdb_t* db, const rocksdb_readoptions_t* options, const char* key,
    size_t keylen, size_t* vallen, char** errptr);
```

const char* means: key is immutable. After returning, RocksDB will not keep reference to the key. And again, the key is only GC-ed when run out of scope -> Safe!
