### ISSUE TITLE
could not determine kind of name for C.rocksdb_options_get_access_hint_on_compaction_start

### ISSUE THREAD

**Issue by chloeyin** [linxGnu/grocksdb#150]
When build with lates RocksDB, this error will be thrown
```
grocksdb@v1.8.6/options.go:1442:33: could not determine kind of name for C.rocksdb_options_get_access_hint_on_compaction_start
```

This API has been deprecated in this [PR](https://github.com/facebook/rocksdb/pull/11654), is it possible to remove this function?

**Comment by linxGnu** [comment]
Which rocksdb version you are on @chloeyin ?

**Comment by chloeyin** [comment]
@linxGnu 
RocksDB 9.1.1

**Comment by linxGnu** [comment]
@chloeyin please use latest release. It support RocksDB 9.1.1

You can find relevant mapping between grocksdb and rocksdb here: https://github.com/linxGnu/grocksdb/releases
