### ISSUE TITLE
Help: about incremental backups?

### ISSUE THREAD

**Issue by xtbwqtq** [linxGnu/grocksdb#158]
Will the ```func (b *BackupEngine) CreateNewBackup()``` method automatically perform incremental backups, or do I need to use something like ```func (b *BackupEngineOptions) ShareTableFiles(flag bool)```?
thnaks!!!!

**Comment by linxGnu** [comment]
@xtbwqtq sorry for late reply. iirc, no auto backup. You need to do it by yourself. Please also ask this question to https://github.com/facebook/rocksdb
