### ISSUE TITLE
How to use this SDK to read the rocksdb sst files and import them to redis?

### ISSUE THREAD

**Issue by GpsLypy** [linxGnu/grocksdb#168]
`
const (
	cFNameDefault = "default"
	//cFNameTest    = "test"
	DB_PATH       = "./backup"
	timestampSize = 8
)

func OpenDB() (*grocksdb.DB, error) {
	opts := grocksdb.NewDefaultOptions()
	opts.SetCreateIfMissing(true)
	db, err := grocksdb.OpenDbForReadOnly(opts, DB_PATH, true)
	if err != nil {
		log.Fatalln("OPEN DB error", db, err)
		db.Close()
		return nil, errors.New("fail to open db")
	} else {
		log.Println("OPEN DB success", db)
	}
	return db, nil
}

func main() {
	logrus.Info("rocksdb test begin")
	db, err := OpenDB()
	if err != nil {
		log.Println("fail to open db,", nil, db)
	}

	ro := grocksdb.NewDefaultReadOptions()
	ro.SetFillCache(false)

	it := db.NewIterator(ro)
	defer it.Close()
	for it.SeekToFirst(); it.Valid(); it.Next() {
		logrus.Info("table_db item name:", string((it.Key().Data())))
		key := it.Key()
		value := it.Value()
		fmt.Printf("Key: %v Value: %v\n", key.Data(), value.Data())
		key.Free()
		value.Free()
	}
	if err := it.Err(); err != nil {
		log.Fatalln("Seek DB error", db, err)
		db.Close()
	}
}
`

**Comment by linxGnu** [comment]
Hi @GpsLypy 

Regarding https://github.com/linxGnu/grocksdb/blob/master/c.h (exposed by RocksDB):
- No API to Read SST Files directly.
