### ISSUE TITLE
Shared lib work in ubuntu but not in docker based alpine

### ISSUE THREAD

**Issue by alx696** [linxGnu/grocksdb#24]
Same code and dockerfile, `github.com/tecbot/gorocksdb` works, grocksdb not. Does it support alpine?

Development environment works:
```
Ubuntu 20.04.1 Linux m-pc 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
RocksDB 6.14.6 build from source use PORTABLE=1 make shared_lib
github.com/linxGnu/grocksdb v1.6.28(with mod)
```

Dockerfile not:
```
FROM registry.cn-shanghai.aliyuncs.com/xm69/alpine-rocksdb-apk AS app
WORKDIR /home
COPY code .
ENV GOPROXY=https://goproxy.cn
RUN set -eux && \
  #设置源
  echo "http://mirrors.ustc.edu.cn/alpine/edge/main/" > /etc/apk/repositories && \
  echo "http://mirrors.ustc.edu.cn/alpine/edge/community/" >> /etc/apk/repositories && \
  echo "http://mirrors.ustc.edu.cn/alpine/edge/testing/" >> /etc/apk/repositories && \
  apk update && \
  #安装RocksDB
  apk add --allow-untrusted /rocksdb.apk /rocksdb-dev.apk && \
  #打印编译环境
  echo "编译环境：$(uname -a)" && \
  #安装Golang环境
  apk add build-base go && \
  #下载并校验Golang模块
  go mod download && go mod verify && \
  #编译Golang应用
  go build -o /home/main
```
> [registry.cn-shanghai.aliyuncs.com/xm69/alpine-rocksdb-apk](https://github.com/alx696/docker-rocksdb-apk)

If use [Static lib](https://github.com/linxGnu/grocksdb#default---builtin-static-linux-only), build failure. Without `-tags` build ok, but can not run.

<details>
 <summary>Error</summary>
pthread set mutex attr: Invalid argument
SIGABRT: abort
PC=0x7f4cf3f92a71 m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f4cf3f92a71
stack: frame={sp:0x7ffe49c331b8, fp:0x0} stack=[0x7ffe49c15480,0x7ffe49c344c0)
00007ffe49c330b8:  000000000000000a  0000000000000000 
00007ffe49c330c8:  00007ffe49c33100  0000000000002710 
00007ffe49c330d8:  0000000000000000  0000000000000000 
00007ffe49c330e8:  00000000009a8000  0000000000000000 
00007ffe49c330f8:  0000000000000000  0000000000000000 
00007ffe49c33108:  00007f4cf3f70eac  0000000000800000 <crypto/tls.(*Config).Clone+32> 
00007ffe49c33118:  0000000000000380  000000000000001b 
00007ffe49c33128:  000000000000001b  0000001400000007 
00007ffe49c33138:  00000000022f2c90  0000000000000004 
00007ffe49c33148:  00007f4cf3f70eac  00000000f3fe0d88 
00007ffe49c33158:  0000000000000020  0000000000000000 
00007ffe49c33168:  00007f4c00000000  0000000000000026 
00007ffe49c33178:  00000000022f46b0  0000000000000001 
00007ffe49c33188:  000000000101dbcb  00007ffe49c332b0 
00007ffe49c33198:  00000000022f4328  00000000013d59f0 
00007ffe49c331a8:  00000000013d7c40  00000000022f4328 
00007ffe49c331b8: <00007f4cf3f92bcc  0000000000000000 
00007ffe49c331c8:  0000003000000010  00007ffe49c332a0 
00007ffe49c331d8:  00007ffe49c331e0  00000000f3fe37c4 
00007ffe49c331e8:  000000000000001f  000000000101dbcb 
00007ffe49c331f8:  00007f4cf3fb1834  0000000000000016 
00007ffe49c33208:  00000000022f4320  0000000000000001 
00007ffe49c33218:  0000000000000040  0000000000000001 
00007ffe49c33228:  0000000000000001  0000000000000040 
00007ffe49c33238:  00000000022f4310  0000000000000008 
00007ffe49c33248:  000000000101dbcb  00007ffe49c332b0 
00007ffe49c33258:  00007f4cf3f6a713  00007f4cf3fe0a80 
00007ffe49c33268:  00007f4cf3f71539  00007ffe49c33370 
00007ffe49c33278:  0000000000b11713  00007ffe49c33310 
00007ffe49c33288:  0000000000000120  000000000101dbcb 
00007ffe49c33298:  0000000000517a38  0000000000000016 
00007ffe49c332a8:  00007ffe49c332c0  00007ffe49c332e0 
runtime: unknown pc 0x7f4cf3f92a71
stack: frame={sp:0x7ffe49c331b8, fp:0x0} stack=[0x7ffe49c15480,0x7ffe49c344c0)
00007ffe49c330b8:  000000000000000a  0000000000000000 
00007ffe49c330c8:  00007ffe49c33100  0000000000002710 
00007ffe49c330d8:  0000000000000000  0000000000000000 
00007ffe49c330e8:  00000000009a8000  0000000000000000 
00007ffe49c330f8:  0000000000000000  0000000000000000 
00007ffe49c33108:  00007f4cf3f70eac  0000000000800000 <crypto/tls.(*Config).Clone+32> 
00007ffe49c33118:  0000000000000380  000000000000001b 
00007ffe49c33128:  000000000000001b  0000001400000007 
00007ffe49c33138:  00000000022f2c90  0000000000000004 
00007ffe49c33148:  00007f4cf3f70eac  00000000f3fe0d88 
00007ffe49c33158:  0000000000000020  0000000000000000 
00007ffe49c33168:  00007f4c00000000  0000000000000026 
00007ffe49c33178:  00000000022f46b0  0000000000000001 
00007ffe49c33188:  000000000101dbcb  00007ffe49c332b0 
00007ffe49c33198:  00000000022f4328  00000000013d59f0 
00007ffe49c331a8:  00000000013d7c40  00000000022f4328 
00007ffe49c331b8: <00007f4cf3f92bcc  0000000000000000 
00007ffe49c331c8:  0000003000000010  00007ffe49c332a0 
00007ffe49c331d8:  00007ffe49c331e0  00000000f3fe37c4 
00007ffe49c331e8:  000000000000001f  000000000101dbcb 
00007ffe49c331f8:  00007f4cf3fb1834  0000000000000016 
00007ffe49c33208:  00000000022f4320  0000000000000001 
00007ffe49c33218:  0000000000000040  0000000000000001 
00007ffe49c33228:  0000000000000001  0000000000000040 
00007ffe49c33238:  00000000022f4310  0000000000000008 
00007ffe49c33248:  000000000101dbcb  00007ffe49c332b0 
00007ffe49c33258:  00007f4cf3f6a713  00007f4cf3fe0a80 
00007ffe49c33268:  00007f4cf3f71539  00007ffe49c33370 
00007ffe49c33278:  0000000000b11713  00007ffe49c33310 
00007ffe49c33288:  0000000000000120  000000000101dbcb 
00007ffe49c33298:  0000000000517a38  0000000000000016 
00007ffe49c332a8:  00007ffe49c332c0  00007ffe49c332e0 

goroutine 1 [syscall]:
runtime.cgocall(0x93e930, 0xc0000cfd88, 0xc0000b6580)
        /usr/lib/go/src/runtime/cgocall.go:133 +0x5b fp=0xc0000cfd58 sp=0xc0000cfd20 pc=0x53d37b
github.com/linxGnu/grocksdb._Cfunc_rocksdb_open(0x22d06a0, 0x22d2120, 0xc0000b6580, 0x0)
        _cgo_gotypes.go:3395 +0x4e fp=0xc0000cfd88 sp=0xc0000cfd58 pc=0x7528ae
github.com/linxGnu/grocksdb.OpenDb.func1(0xc0000afa80, 0x22d2120, 0xc0000b6580, 0xc0000ec000)
        /root/go/pkg/mod/github.com/linx!gnu/grocksdb@v1.6.28/db.go:37 +0xa7 fp=0xc0000cfdc0 sp=0xc0000cfd88 pc=0x775347
github.com/linxGnu/grocksdb.OpenDb(0xc0000afa80, 0xc0000b4d80, 0xc, 0xc0000b4d80, 0xc, 0x0)
        /root/go/pkg/mod/github.com/linx!gnu/grocksdb@v1.6.28/db.go:37 +0x7a fp=0xc0000cfe20 sp=0xc0000cfdc0 pc=0x762e3a
main.main()
        /home/main.go:673 +0x870 fp=0xc0000cff88 sp=0xc0000cfe20 pc=0x93bff0
runtime.main()
        /usr/lib/go/src/runtime/proc.go:204 +0x209 fp=0xc0000cffe0 sp=0xc0000cff88 pc=0x571a69
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0000cffe8 sp=0xc0000cffe0 pc=0x5a3461

rax    0x0
rbx    0x0
rcx    0x7f4cf3f92a71
rdx    0x0
rdi    0x2
rsi    0x7ffe49c331c0
rbp    0x7ffe49c331c0
rsp    0x7ffe49c331b8
r8     0x7f4cf3fe00c0
r9     0x7f4cf3fdd933
r10    0x8
r11    0x246
r12    0x22f4328
r13    0x13d59f0
r14    0x13d7c40
r15    0x22d26f8
rip    0x7f4cf3f92a71
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
</details>

**Comment by linxGnu** [comment]
@alx696 thank you very much for trying grocksdb.

Yeah, builtin static lib at the moment is limited to libc, not musl compatible with alpine.

So, I think you could:
- Build rocksdb as static lib inside your alpine image
- Build grocksdb and your application: `go build -tags static`

Or, if you want shared lib:
- Build rocksdb as shared lib inside your alpine image
- Build grocksdb and your applicaion: `go build`

Please tell me if that works for you.

**Comment by alx696** [comment]
@linxGnu Thanks very much for your response. After add CGO_CFLAGS and CGO_LDFLAGS, it works. 

Dockerfile:
```
FROM registry.cn-shanghai.aliyuncs.com/xm69/alpine-rocksdb-apk AS app
WORKDIR /home
COPY code .
ENV GOPROXY=https://goproxy.cn
RUN set -eux && \
  #设置源
  echo "http://mirrors.ustc.edu.cn/alpine/edge/main/" > /etc/apk/repositories && \
  echo "http://mirrors.ustc.edu.cn/alpine/edge/community/" >> /etc/apk/repositories && \
  echo "http://mirrors.ustc.edu.cn/alpine/edge/testing/" >> /etc/apk/repositories && \
  apk update && \
  #安装RocksDB
  apk add --allow-untrusted /rocksdb.apk /rocksdb-dev.apk && \
  #打印编译环境
  echo "编译环境：$(uname -a)" && \
  #安装Golang环境
  apk add build-base go && \
  #下载并校验Golang模块
  go mod download && go mod verify && \
  #编译Golang应用
  # https://github.com/linxGnu/grocksdb/issues/24#issuecomment-752988851
  CGO_CFLAGS="-I/usr/include/rocksdb" \
  CGO_LDFLAGS="-L/usr/lib -lrocksdb -lstdc++ -lm -lz -lsnappy -llz4 -lzstd" \
  go build -o /home/main
```
> If your CPU support SSE4.2, you can use [rocksdb packages in alpine](https://pkgs.alpinelinux.org/packages?name=rocksdb&branch=edge).

Shared library is smaller than static lib, especially in alpine. And [rocksdb packages in alpine](https://pkgs.alpinelinux.org/packages?name=rocksdb&branch=edge) is also compiles shared library.

No need to `go get -u github.com/linxGnu/grocksdb` when Using Go Modules. Just install RocksDB first.

Ubuntu Install RocksDB:
```
$ sudo apt install -y libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev
$ PORTABLE=1 make -j32 shared_lib
$ sudo make install-shared
$ sudo su
# echo "/usr/local/lib" >> /etc/ld.so.conf
# ldconfig
```
