### ISSUE TITLE
Support for Eventlistener?

### ISSUE THREAD

**Issue by muXxer** [linxGnu/grocksdb#28]
Hello!

First I really like to thank you for your awesome work.
This is outstanding!

We will switch our open source project after months of trying badger, boltdb, pebbledb to your lib I guess.
For our usecase rocksdb it much faster with less CPU and Memory usage.
 
The only thing I can't find is a way to register the EventListener:
https://github.com/facebook/rocksdb/blob/29e8f6a698acf0d00d88f21a2692fcdd974a74e5/include/rocksdb/listener.h#L358

Do I miss something, or is there no way yet?

Especially the compaction events would be nice for our usecase, to know when compaction is running in the background:

https://github.com/facebook/rocksdb/blob/29e8f6a698acf0d00d88f21a2692fcdd974a74e5/include/rocksdb/listener.h#L400
https://github.com/facebook/rocksdb/blob/29e8f6a698acf0d00d88f21a2692fcdd974a74e5/include/rocksdb/listener.h#L415

Can you give me a hint how to implement this if it is missing?
Thank you for your help!

**Comment by linxGnu** [comment]
@muXxer I am afraid that it's not possible at the moment now. RocksDB has not expose any `C` extern func for this feature yet.

May I ask you why you need this kind of functionality? For stats/metrics monitoring?

**Comment by muXxer** [comment]
Before using your lib we used pebbledb, and there we have callbacks when the compaction starts and ends, which we expose via prometheus/grafana to show some metrics.

This way we can clearly see why the disc is under high low when the compaction starts. 
I was just wondering if that may be possible with rocksdb as well. :)

![image](https://user-images.githubusercontent.com/32371094/111890967-c5483e80-89ee-11eb-8f92-529dd3af69da.png)

**Comment by linxGnu** [comment]
@muXxer that's totally make sense. In this way, I guess you could parse statistic to get those metrics.

Please kindly refer to this document: https://www.bookstack.cn/read/rocksdb-en/b0fd8fb2013f7771.md#RocksDB%20statistics

And use following function: https://github.com/linxGnu/grocksdb/blob/22c6c96a4a2c28e56e5c9c1708e465493dec1028/db.go#L832

You have to parse the statistic before real using. But I think it's worth to do so :) Please let me know if this approach works for you. Thank you

**Comment by linxGnu** [comment]
Another document you might want to take a look: https://github.com/facebook/rocksdb/wiki/Statistics

**Comment by linxGnu** [comment]
In this way, everytime Prometheus invoke your http endpoint to scrape your metrics, you might:
1. Get `rocksdb.stats`
2. Parsing -> metrics
3. Update that metrics
4. Invoke prometheus handler 

Simpler way: write a custome Prometheus metric collector. With custom collector, you don't have to do above 4 steps

**Comment by muXxer** [comment]
Thank you very much for all your help. I got it running with `GetIntProperty("rocksdb.num-running-compactions")` :)
