### ISSUE TITLE
How do you do GetCfHandle() ?

### ISSUE THREAD

**Issue by hiqsociety** [linxGnu/grocksdb#40]
Possible to provide the code to add this function in?

**Comment by linxGnu** [comment]
@hiqsociety what functionality do you really want?

**Comment by hiqsociety** [comment]
sorry for asking, but saw this 
cfhandle := GetCFHandle("something") <- returning the cfhandle for the name

https://github.com/bitleak/kvrocks/blob/cdb0ccedd36f21432977b8a9d0bac7f4a2a1e84e/src/storage.cc#L445

not sure if it's possible with default rocksdb function

**Comment by hiqsociety** [comment]
because i dont want to list all the cfnames and then just to open one.

**Comment by linxGnu** [comment]
There is no functionality like this exposed by RocksDB @hiqsociety

**Comment by hiqsociety** [comment]
ok. any ideas if we can achieve this with golang? otherwise need to write the code of 
https://github.com/bitleak/kvrocks/blob/cdb0ccedd36f21432977b8a9d0bac7f4a2a1e84e/src/storage.cc#L445
in?

**Comment by linxGnu** [comment]
@hiqsociety It's impossible if rocksdb does not support this functionality. At the moment, it doesn't.

Your sample code above:
```c++
rocksdb::ColumnFamilyHandle *Storage::GetCFHandle(const std::string &amp;name) {  
   if (name == kMetadataColumnFamilyName) {    return cf_handles_[1];  } 
   else if (name == kZSetScoreColumnFamilyName) {    return cf_handles_[2];  } 
   else if (name == kPubSubColumnFamilyName) {    return cf_handles_[3];  }  
return cf_handles_[0];}
```

`cf_handles_` are opened column families while opening the db.

**Comment by hiqsociety** [comment]
thx
