### ISSUE TITLE
I've looked at options.go but do you know if there's a way to access the WAL records/content?

### ISSUE THREAD

**Issue by hiqsociety** [linxGnu/grocksdb#43]
i would like to manually get the lines of WAL records / content to use as a customized replication log for rocksdb replication.

do you know how i can access wal? i can provide the code of which to do replication once i'm done with it

**Comment by linxGnu** [comment]
I am afraid that you can't get WAL contents. By default, Rocksdb opens up many WAL files at the same time.

One way to perform replication is over: snapshot / restore. You could search for it.
