### ISSUE TITLE
Do you have a transaction tests for column families?

### ISSUE THREAD

**Issue by hiqsociety** [linxGnu/grocksdb#47]
possible to provide example on how to achieve transactions with column families? and/or optimistic transactions with cf too. thx

mentioned coz i didnt see any test with examples inside.

**Comment by linxGnu** [comment]
@hiqsociety please refer to rocksdb documentation: https://github.com/facebook/rocksdb/wiki/Transactions

> Note that RocksDB provides Atomicity by default when writing multiple keys via WriteBatch. Transactions provide a way to guarantee that a batch of writes will only be written if there are no conflicts
