### ISSUE TITLE
hi, this file is not available. can you pls provide it again?

### ISSUE THREAD

**Issue by hiqsociety** [linxGnu/grocksdb#48]
https://github.com/linxGnu/grocksdb/blob/try_terark/docker/Dockerfile#L12-L20

thx

**Comment by linxGnu** [comment]
Ah yes, I deleted `try_terark` branch long time ago. Once again, I don't think I `grocksdb` should support `terarkdb` at any corner.
Could you please make it yourself.

**Comment by hiqsociety** [comment]
what's the dockerfile like? sry pls provide it again

why did u delete terarkdb just curious?

**Comment by linxGnu** [comment]
@hiqsociety the dockerfile is for quick setting up env and try to install terark.

However, supporting terarkdb is not my duty and reponibility. There is no reason to keep that broken branch in the repository.

if you want it, you should request me to keep it long time ago. Actually, I kept that branch for months, but no request of keeping it.
