### ISSUE TITLE
hi can you be kind enough to re-provide the docker file again?

### ISSUE THREAD

**Issue by hiqsociety** [linxGnu/grocksdb#51]
can you pls provide the terarkdb docker file for reference? thx in advance.

**Comment by linxGnu** [comment]
Hello @hiqsociety 

`terarkdb` is not my responsibility. Please ask `terarkdb` team to support your build.

Once again, let's say:
1. I already did provide `terarkdb` toy-building and leave it as a `branch` for a while
2. You did not ask me to keep or anything else.
3. There is no reason why you continue to ask me to support a kind of broken product like `terarkdb`
4. `terarkdb` build documentation is pretty ugly:
  - Lack of information that they used their own boost library
  - Too many dependencies
5. `terarkdb` lack of important features, outdated compare to `rocksdb`
6. `rocksdb` is robust, feature rich and even provide a `lite` version for small devices

Please do not spam my repository to ask about `terarkdb`. Please hook your questions to `terarkdb` GitHub repo, not mine.

**Comment by superdolt** [comment]
ok thx. appreciate your feedback i didnt know u would delete the branch that's all. because you also didnt mention you wouldnt.

**Comment by hiqsociety** [comment]
ok thx. appreciate your feedback i didnt know u would delete the branch that's all. because you also didnt mention you wouldnt.

anyhow, thank you for helping to get it to work. if you have the branch, pls do zip it and post it online so we can back reference.

really appreciate this. great work on grocksdb. it's impressive.

**Comment by superdolt** [comment]
can u pls share why u say terarkdb is broken? TerarkDB is compatible with RocksDB 5.x. 

other than that, it doesnt support all features of the latest rocksdb version that's all
