### ISSUE TITLE
Can't call the method "CreateColumnFamilyWithTTL",  build error _Ctype_int errorr

### ISSUE THREAD

**Issue by binyoyo** [linxGnu/grocksdb#52]
in project，call the method CreateColumnFamilyWithTTL, build error _Ctype_int

![image](https://user-images.githubusercontent.com/3898451/133016788-2af321c2-d2af-45ee-82b2-64a5e5d9ed79.png)

![image](https://user-images.githubusercontent.com/3898451/133016549-d1371660-197e-4d15-90e9-70e907c497ea.png)

i change the package code param type (C.int to int), and in the project call the method by int param, to fixed the error
![image](https://user-images.githubusercontent.com/3898451/133017119-e0c747df-ffc4-4340-aba2-02a20ce302cd.png)

![image](https://user-images.githubusercontent.com/3898451/133017001-c010c46c-3588-4c9e-926b-f6ae4f7918a2.png)

@linxGnu

**Comment by linxGnu** [comment]
oh thank you for pointing out. I will update the function signature and let you know

**Comment by linxGnu** [comment]
@binyoyo I have just release v1.6.38 which fixes the function signature. PTAL
