### ISSUE TITLE
go test failed

### ISSUE THREAD

**Issue by g302ge** [linxGnu/grocksdb#61]
I met this bug when I start the go test to run the inner unit test I got the error told me that I have no linked with Lz4 or other Lib, Why cause this error ?

**Comment by LeeMaster** [comment]
I think in current situation using rocksdb in Go, we need a way to dump the options from the rocksdb kernel. Though the origin c.h doesn't support interface to access them .

**Comment by linxGnu** [comment]
@LeeMaster 

It will be impossible for me to help you if you do not provide any error logs and your build env.

Please take a look at my build script for dependencies like LZ4: https://github.com/linxGnu/grocksdb/blob/master/build.sh

In this way, you could update lib location to yours `INSTALL_PREFIX=$1` (this one, it could be `/usr/local` if you want)

**Comment by LeeMaster** [comment]
But the strangry thing is that When I build the total lib with go build there is no error. But When I using the go test -v , will error

**Comment by linxGnu** [comment]
@LeeMaster could you please give me your logs while running `go test -v`, and step by step of what you did. I would like to reproduce at my side.
