### ISSUE TITLE
i did the dbr.CompactRange(grocksdb.Range{nil, nil}) to trigger manual compaction but hv error below

### ISSUE THREAD

**Issue by hiqsociety** [linxGnu/grocksdb#74]
i did the dbr.CompactRange(grocksdb.Range{nil, nil}) to trigger manual compaction but hv error below

dbr.CompactRange(grocksdb.Range{nil, nil}) (no value) used as value

i saw the code in _test so just copied and paste but doesnt work.

how to make it work? thx in advance

**Comment by linxGnu** [comment]
I am sorry for late reply. Could you please show me full error and your code. Thank

**Comment by linxGnu** [comment]
I will close the ticket. Please feel free to reopen if you are still in trouble.
