### ISSUE TITLE
no DeleteFilesInRange api

### ISSUE THREAD

**Issue by meilihao** [linxGnu/grocksdb#78]

**Comment by linxGnu** [comment]
@meilihao Could you please describe your issue

**Comment by linxGnu** [comment]
@meilihao Could you please take a look at function `DeleteFileInRange` (no `s`)

**Comment by meilihao** [comment]
I'am not found DeleteFilesInRange api.

**Comment by linxGnu** [comment]
@meilihao here it is: https://github.com/linxGnu/grocksdb/blob/aac6cb380722018cbec5138b309bd1c51930b986/db.go#L1602-L1621

**Comment by meilihao** [comment]
I'm all wrong, I just grep the wrong place
