### ISSUE TITLE
Add rocksdb sources to the go package

### ISSUE THREAD

**Issue by anatol** [linxGnu/grocksdb#90]
Hi y'all,

I am trying to use this package for my go project and I found its installation/setup procedure quite complicated. By default the package gives following compilation error:

```
➜  rocksdb go build
# github.com/linxGnu/grocksdb
../../go/pkg/mod/github.com/linx!gnu/grocksdb@v1.7.7/array.go:4:11: fatal error: rocksdb/c.h: No such file or directory
    4 | // #include "rocksdb/c.h"
      |           ^~~~~~~~~~~~~
compilation terminated.
```

To use `grocksdb` bindings  additional steps are required to compile rocksdb and its dependencies.

A better solution would be to let cgo compile the rocksdb sources. Similar to how [sqlite3 go bindings](https://github.com/mattn/go-sqlite3) do. cgo just picks *.c files stored together with go sources then compiles and automatically links it.

This requires an amalgamation file (i.e. a single file that contains all project sources) to be provided by rocksdb project (like sqlite does). It turns out rocksdb has a tool for that https://github.com/facebook/rocksdb/blob/main/build_tools/amalgamate.py that aim to achieve what we need.

**Comment by linxGnu** [comment]
@anatol Adding rocksdb and its dependency code base makes the repository heavy and makes compile time much higher than before. 

Not only that, RocksDB is not C but C++. Making go <> c++ interoperability is very high cost.

**Comment by anatol** [comment]
> @anatol Adding rocksdb and its dependency code base makes the repository heavy and makes compile time much higher than before.

True, rocksdb is a heavy dependency and requires a lot of time to compile unfortunately.

> Not only that, RocksDB is not C but C++. Making go <> c++ interoperability is very high cost.

You already use this C++-C bridge with your CGO method. Using amalgamated sources does not change anything here. In fact, joining sources into one compilation unit let's compiler use more optimizations.

**Comment by yihuang** [comment]
it's pretty easy to manage c dependencies with nix, but need this small change to build though: https://github.com/linxGnu/grocksdb/pull/100

**Comment by linxGnu** [comment]
I will close this ticket. Thank you all for the suggestion.
