### ISSUE TITLE
Documentation fix: Add -lbz2 link flag

### ISSUE THREAD

**Issue by aureliar8** [linxGnu/grocksdb#91]
On ubuntu22, I had to add `-lbz2` to the `CGO_LDFLAGS` to successfully run `go build`

I'd suggest to add it in the Readme build flags:
```
CGO_CFLAGS="-I/path/to/rocksdb/include" \
CGO_LDFLAGS="-L/path/to/rocksdb -lrocksdb -lstdc++ -lm -lz -lsnappy -llz4 -lzstd -lbz2" \
  go build
``` 

Thanks fro your work

**Comment by linxGnu** [comment]
Thank you for suggestion. I think it's reasonable to update the README. 

To clarify why bz2 is needed by your case:
- your rocksdb was built with bz2 support
- it's root cause why you need to specify bz2 link

**Comment by linxGnu** [comment]
I updated README. Thank you.
