### ISSUE TITLE
cannot use _Ctype_ulong(s) (value of type _Ctype_ulong) as type _Ctype_ulonglong in variable declaration

### ISSUE THREAD

**Issue by peacess** [linxGnu/grocksdb#93]
v1.7.7   rocksdb v7.5.3
can not build in windows

grocksdb@v1.7.7\cache.go:79:74: cannot use _Ctype_ulong(s) (value of type _Ctype_ulong) as type _Ctype_ulonglong in variable declaration
grocksdb@v1.7.7\options.go:1569:96: cannot use _Ctype_ulong(windowSize) (value of type _Ctype_ulong) as type _Ctype_ulonglong in variable declaration
grocksdb@v1.7.7\options.go:1569:117: cannot use _Ctype_ulong(numDelsTrigger) (value of type _Ctype_ulong) as type _Ctype_ulonglong in variable declaration

**Comment by linxGnu** [comment]
@peacess thank you very much for reporting the bug.
Please checkout version: https://github.com/linxGnu/grocksdb/tree/v1.7.9 which includes the fix. 

Note: I don't have Window here, please let me know if it works
