### ISSUE TITLE
need rocksdb_column_family_handle_get_name 

### ISSUE THREAD

**Issue by jyialive** [linxGnu/grocksdb#99]

**Comment by linxGnu** [comment]
@jyialive
rocksdb_column_family_handle_get_name api was introduced recently. 

You can use my branch: https://github.com/linxGnu/grocksdb/tree/adapt_rocksdb7.7.3

**Comment by linxGnu** [comment]
I did not release a new version as waiting for RocksDB 7.7.x to be stable. Usually after 2 months

**Comment by linxGnu** [comment]
As RocksDB 7.7.x adoption was released, I will close this issue. 

The api was fully supported: https://github.com/linxGnu/grocksdb/blob/master/cf_handle.go#L23-L27
